version: 2

jobs:
  checkout_code:
    working_directory: /home/circleci/ObjectUtils

    docker:
      - image: circleci/node:10.14

    steps:
      - checkout

      - save_cache:
          key   : repo-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
          paths :
            - ./

  node_dependencies:
    working_directory: /home/circleci/ObjectUtils

    docker:
      - image: circleci/node:10.14

    steps:
      - restore_cache:
          key: repo-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}

      - restore_cache:
          key: node-cache-{{ .Branch }}-{{ checksum "package.json" }}

      - run:
          name    : Installing npm dependencies
          command : npm install

      - save_cache:
          key   : node-cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths :
            - ./node_modules

  tests:
    working_directory: /home/circleci/ObjectUtils

    docker:
      - image: circleci/node:10.14

      - image: mongo:3.6.8

      - image: redislabs/rejson:latest

    steps:

      - restore_cache:
          key: repo-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}

      - restore_cache:
          key: node-cache-{{ .Branch }}-{{ checksum "package.json" }}

      - run:
          name    : Waiting for MongoDB
          command : dockerize -wait tcp://localhost:27017 -timeout 1m

      - run:
          name    : Waiting for Redis
          command : dockerize -wait tcp://localhost:6379 -timeout 1m

      - run:
          name    : Running unit tests
          command : npm run test

      - store_artifacts:
          path    : test-results.xml
          prefix  : tests

      - store_artifacts:
          path    : coverage
          prefix  : coverage

      - store_test_results:
          path: test-results.xml

      - save_cache:
          key   : test-coverage-cache-{{ .Environment.CIRCLE_SHA1 }}
          paths :
            - ./coverage

  npm_publish:
    working_directory: /home/circleci/ObjectUtils

    docker:
      - image: circleci/node:10.14
    
    steps:
      - restore_cache:
          key: repo-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}

      - restore_cache:
          key: node-cache-{{ .Branch }}-{{ checksum "package.json" }}

      - run:
          name: Token
          command: echo $NPM_TOKEN

      - run:
          name: Authenticating with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc

      - run:
          name: Publishing package
          command: npm publish

workflows:
  version: 2

  build-and-deploy:
    jobs:
      - checkout_code

      - node_dependencies:
          requires:
            - checkout_code

      - tests:
          requires:
            - node_dependencies

      - npm_publish:
          filters:
            tags:
              only: /^v.*/
            branches:
              only: master
          requires:
            - tests
      
      - docs_upload:
          requires:
            - npm_publish